pipepline {
  agent any

  tools{maven 'maven 3.9.8')
  
  stages{
	stage{"build"}{
		steps{
			echo 'Compiling worker app'
			dir('woker'){
				sh 'mvn compile'
			}
		}
	}
	
	stage("test"){
		steps{
			echo 'Running Unit Test on worker app'
		}
	}
	
	stage("package"){
		steps{
			echo 'Packaging app'
		}
	}

	post{ always{echo 'Building multibranch pipeline for worker is completed..'}}
}

